---
title: "Data Import"
output: github_document
Author: Adam R
editor_options: 
  chunk_output_type: console
---
```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## read in some data

read in the litters dataset.

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Take a look at the data

printing in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

## Options to read_csv

check out '?read_csv' for more info.

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
```

## other file formats

read in an excel file

```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx", range = "A1:F7")
mlb_df
```

read in a sas file

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
```

## Comparison with base r

what about 'read.csv' ...?

```{r}
litters_base = read.csv("./data_import_examples/FAS_litters.csv")
litters_readr = read_csv("./data_import_examples/FAS_litters.csv")

litters_base
litters_readr
```

## Exporting data

export the mlb subtable

```{r}
write_csv(mlb_df, "./data_import_examples/mlb_subtable.csv")
```



